### PR TITLE
Updated model information

### PR DESCRIPTION
**Pull request by peternijssen**
Added the information known so far about the different devices. I was doubting about renaming the model names, as this might be a breaking change, but I think we should do it at a certain point. Looking at Home Assistant, it's cleaner to show the actual name rather than some sort of abbreviation. I think the recent merges also had some breaking changes, so better to introduce all at once.

If you do believe it should be done differently and I should leave the original get_model() response alone, let me know as that was your original request.

Also changed the if-else to an early return and letting the model and manufacturer method always return something (Fallback to unknown).

Kept the get_model and added the get_manufacturer method, as Home Assistant is using those terms.

If the PR is fine, I will fix ruff and the tests and do a final test.

### CODE REVIEW

**Comment by erikmol** [comment]
Great work! As I [previously pointed out](https://github.com/alistair23/AutoMower-BLE/pull/30#issuecomment-2083601939) in #30, I'm a bit skeptical to having all un-mapped devices show up as "`Series` `Unknown`". Wouldn't it be good to include the keys so that feedback easily can be given to the developers of this repo? I.e. 
`((14, 2), ModelInformation("Gardena", "SILENO City Unknown")),`
becomes something like
`((14, 2), ModelInformation("Gardena", "SILENO City Unknown (14,2)")),`

**Comment by peternijssen** [comment]
Good point! Also made the `get_model()` and `get_manufacturer()` methods more explicit so we get feedback in case of new devices we are currently unaware off.

**Comment by peternijssen** [comment]
As expected this is a breaking change for Home Assistant as the entities are recreated. It does look like expected however :)

Scherm­afbeelding 2024-05-08 om 17 45 58

**Review by alistair23 — APPROVED** [review]

**Review by alistair23 — APPROVED** [review]

**Comment by gingemonster** [comment]
What's the best way to fill in a gap for an unknown device, update the models myself and do a PR? 

My "SILENO city 500m²" https://www.gardena.com/int/products/lawn-care/robotic-lawnmowers/robotic-mower-sileno-city-500-m/967647206.html comes up as:

SILENO City Unknown (14,6)

**Comment by peternijssen** [comment]
@gingemonster replace `Unknown (14,6)` with `500` in a Pr. See 14,1 as an example, which is the sileno city 250.

**Pull request merged**
