### PR TITLE
added extra requests and responses and added usage in mower

### PR DESCRIPTION
**Pull request by enicky**
split up big PR into smaller pieces.

Part 1 : Added several requests and responses to be able to process more data coming from the mower.

I followed the requests / responses coming from the Gardena Minimo to be able to recreate all requests that were sent from the mobile phone. 

Also implemented tests to be able to test them.

### CODE REVIEW

**Comment by alistair23** [comment]
Would it be too much to ask you to port this on top of https://github.com/alistair23/AutoMower-BLE/pull/15?

I know that's a bit of a pain.

Also, you aren't actually using these new commands when making a connection?

**Comment by enicky** [comment]
> Would it be too much to ask you to port this on top of https://github.com/alistair23/AutoMower-BLE/pull/15?

That was the reason why I asked if I had to continue on your code or on @erikmol 's 😉. But no worries. I'll do these changes based on @erikmol PR.

> Also, you aren't actually using these new commands when making a connection?

Well I'm using them in another PR that was coming where I have a script that represents all the commands that were being sent from my Gardena App. I couldn't get your code to work with the Minimo so I implemented them all 😁 (well all ... all that were being sent while starting / pausing / resuming / parking). 

I also finalized the "get task" command. But I'll add that one to the port for #15 

Do you want me to close this PR ? (after I ported everything 😉)

**Comment by alistair23** [comment]
> That was the reason why I asked if I had to continue on your code or on @erikmol 's 😉. But no worries. I'll do these changes based on @erikmol PR.

Yeah... That's my fault there. I didn't realise you would add so many new requests! I thought you were just testing and sent a small patch.

Sorry about that. I hope it isn't too hard to rebase.

> Well I'm using them in another PR that was coming where I have a script that represents all the commands that were being sent from my Gardena App. I couldn't get your code to work with the Minimo so I implemented them all 😁 (well all ... all that were being sent while starting / pausing / resuming / parking).

Do you need them for the Gardena mower to work? If so we should set it up to run as part of the HA setup, so then it will work for others.

> Do you want me to close this PR ? (after I ported everything 😉)

If you can just rebase this PR as is then I can merge it and we can go from there

**Comment by enicky** [comment]
I'm closing this PR, because I created a new one with only the requests / responses aka Commands in a new PR : #33 

It was easier to do it that way because @erikmol already implemented a few of the other commands.

**Pull request closed without merging**
