### PR TITLE
Add Sileno City 250 (Gardena)

### PR DESCRIPTION
**Pull request by peternijssen**
Adding the Sileno City 250 based on analysis of my own lawn mower.

Reviewing the decompiled Gardena app, I noticed the following types and variants:

> - MowerModel.Type14.Variant1.INSTANCE
> - MowerModel.Type14.Variant2.INSTANCE
> - MowerModel.Type14.Variant3.INSTANCE
> - MowerModel.Type14.Variant4.INSTANCE
> - MowerModel.Type14.Variant5.INSTANCE
> - MowerModel.Type14.Variant6.INSTANCE
> - SmartMowerModel.Type14.Variant7.INSTANCE
> - SmartMowerModel.Type14.Variant8.INSTANCE
> - MowerModel.Type14.Variant9.INSTANCE
> - MowerModel.Type14.Variant10.INSTANCE
> - MowerModel.Type14.Variant11.INSTANCE
> - SmartMowerModel.Type14.Variant12.INSTANCE
> - MowerModel.Type14.Variant13.INSTANCE
> - SmartMowerModel.Type14.Variant14.INSTANCE
> - SmartMowerModel.Type14.Variant15.INSTANCE
> - SmartMowerModel.Type14.Variant16.INSTANCE
> - SmartMowerModel.Type14.Variant17.INSTANCE
> - MowerModel.Type14.Variant18.INSTANCE

> - MowerModel.Type18.Variant1.INSTANCE
> - MowerModel.Type18.Variant2.INSTANCE
> - MowerModel.Type18.Variant3.INSTANCE
> - SmartMowerModel.Type18.Variant4.INSTANCE
> - SmartMowerModel.Type18.Variant5.INSTANCE
> - SmartMowerModel.Type18.Variant6.INSTANCE
> - MowerModel.Type18.Variant7.INSTANCE
> - MowerModel.Type18.Variant8.INSTANCE
> - SmartMowerModel.Type18.Variant9.INSTANCE
> - SmartMowerModel.Type18.Variant10.INSTANCE
> - SmartMowerModel.Type18.Variant11.INSTANCE
> - MowerModel.Type18.Variant12.INSTANCE
> - MowerModel.Type18.Variant13.INSTANCE
> - SmartMowerModel.Type18.Variant14.INSTANCE
> - SmartMowerModel.Type18.Variant15.INSTANCE
> - MowerModel.Type18.Variant16.INSTANCE
> - SmartMowerModel.Type18.Variant17.INSTANCE

> - MowerModel.Type29.Variant1.INSTANCE
> - MowerModel.Type29.Variant2.INSTANCE
> - MowerModel.Type29.Variant3.INSTANCE
> - MowerModel.Type29.Variant4.INSTANCE
> - MowerModel.Type29.Variant5.INSTANCE
> - MowerModel.Type29.Variant6.INSTANCE
> - MowerModel.Type29.Variant7.INSTANCE
> - MowerModel.Type29.Variant8.INSTANCE
> - MowerModel.Type29.Variant9.INSTANCE
> - MowerModel.Type29.Variant10.INSTANCE

I suspect Type14 is Sileno City and Type 29 is Minimo. The only one missing then is Sileno Life, which probably is Type 18.

Would it be good to all all these types and variants already to the list of models with maybe a name like "Unknown"?
Would it be good to make a manufacturer to every model (like husqvarna, gardena, flymo, mccullogh)? That would help setting the right manufacturer and model in HA (https://developers.home-assistant.io/docs/device_registry_index/)

### CODE REVIEW

**Comment by alistair23** [comment]
It probably makes sense to add the Gardena models all at once. It seems like they are all the same and work pretty fell.

Adding the manufacturer information somewhere is also a good idea

**Comment by erikmol** [comment]
I also took a look at the gardena apk but also found type/variants `22,[1-4]` and `25,[1-4]`.

> Would it be good to all all these types and variants already to the list of models with maybe a name like "Unknown"? 

I think It would be good to have unknown variants listed as `Unknown-22-1` to get feedback on the mapping.

In general, it would probably also be good to have information about commands/features of the various mowers. For instance, some mowers allow for cutting height to be set while simpler models have this as a physical adjustment knob.

**Comment by peternijssen** [comment]
> It probably makes sense to add the Gardena models all at once. It seems like they are all the same and work pretty fell.
> 
> Adding the manufacturer information somewhere is also a good idea

Happy to contribute, but I am not an enormous python guru. If someone can point me in the right direction how we envision this I am happy to give it a go. Or someone else can create it :)

**Comment by peternijssen** [comment]
> I also took a look at the gardena apk but also found type/variants `22,[1-4]` and `25,[1-4]`.
 
Good catch! However it's not within the SupportedModels method:
`
    public final List<ProductModel> getAllSupportedModels() {
        List<ProductModel> arrayList = new ArrayList<>();
        arrayList.addAll(CollectionsKt.mutableListOf(....));
        return arrayList;
    }`

> I think It would be good to have unknown variants listed as `Unknown-22-1` to get feedback on the mapping.
> 
> In general, it would probably also be good to have information about commands/features of the various mowers. For instance, some mowers allow for cutting height to be set while simpler models have this as a physical adjustment knob.

Agree. There is a class called MowerCapabilities.java that contains a list of which options are available per mower. Happy to see if I can translate to a sheet so we have devices and capabilities listed.

**Comment by peternijssen** [comment]
work in progress:

Took a moment to decompile the McCulloch and Flymo app and that's where 22 and 25 are. So here is a full list:

* `14,[1-18]` Gardena - Sileno City
* `18,[1-17]` Gardena - Sileno Life?
* `29,[1-10]` Gardena - Minimo
* `22,[1-4]` McCulloch - Rob
* `25,[1-4]` Flymo - Easilife?
* `30,[1-5]` Flymo - Easilife Go?

Assumptions made:
Flymo has an Easilife, Easilife Go and Ultralife line. Ultralife is not mentioned in the decompiled app. Easilife Go has 5 models, Easilife has 4 models.

(Do we need a wiki to document this?)

**Comment by peternijssen** [comment]
@alistair23 What would you like to do? Basically the PR as is can be accepted, we just need to make a plan how to define information? I am thinking about "Manufacturer" and "Model". I also thought you could go with "Series" like "Sileno City" as the serie, but looking at the Automower, there is hardly any serie like Gardena and others, so it seems overkill.

Should we create an object ModelInformation like in https://github.com/alistair23/AutoMower-BLE/pull/24 (except a boolean, it's actually the Manufacturer? Because then I am happy to start working on it. Just looking for the best way forward to organise it :)

**Comment by alistair23** [comment]
On one hand the BLE GATTs should tell us the Manufacturer and the series. The Husqvarna ones for example specify the Manufacturer as Husqvarana (via a UID) and one of the GATTS say "Automower". So ideally we want to probe that information from the actual mower.

In saying that I think we should include Manufacturer details in the list somewhere. That way it's easier for a human to read it and understand what is going on.

So maybe include the manufacture and series in the list, similar to https://github.com/alistair23/AutoMower-BLE/pull/24.

Probably heave `get_model()` return just the model string (as it does today) and add a new function  to return all of the information. That way we don't break compatibility.

**Comment by peternijssen** [comment]
Closing this one in favor of https://github.com/alistair23/AutoMower-BLE/pull/42

**Pull request closed without merging**
