### PR TITLE
added functionality to be able to switch between state mappings

### PR DESCRIPTION
**Pull request by enicky**
Modified the MowerModel to be able to add a boolean to map to a different mower state mapping.

Gardena ones apparently have a different mapping.

Made sure it is backwards compatible and added tests.

### CODE REVIEW

**Comment by alistair23** [comment]
I think we should sort out https://github.com/alistair23/AutoMower-BLE/issues/13 first. It's possible that the current state mappings are just wrong and we don't need this PR.

**Comment by enicky** [comment]
I can remove the PR if you want to ? It's not that big ... and have the code still locally.

**Comment by peternijssen** [comment]
Apart from if the mower state is different or not between mowers, it might be good anyway to update the models class with the actual vendor (Husqvarna, Gardena, Flymo, McCulloch)?

**Comment by alistair23** [comment]
Yeah, that's probably worth doing as we are supporting more and more non-Husqvarna branded mowers

**Comment by enicky** [comment]
Closing PR.

**Pull request closed without merging**
